#!/usr/bin/env bash
# Script to install and configure HAproxy

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
        timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.224.17.212:80 check
    server web-02 3.94.181.134:80 check
EOF

# Restart HAproxy
sudo systemctl restart haproxy

